name: pipeline

on:
  push:
    branches: ['devlop']
  pull_request:
    branches: ['devlop']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configurer Docker Buildx (support multi-plateforme)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Lancer les services avec Docker Compose
      - name: Start services
        run: docker-compose up -d

      # Exécuter les tests du backend (Express.js)
      - name: Run backend tests
        run: |
          docker exec $(docker ps -qf "name=app") npm test

      # Se connecter à Docker Hub
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      # Construire et pousser les images Docker du backend et du frontend
      - name: Build and push backend image
        run: |
          docker build -t cherkaoui97/labmetrixis_fillrouge_backend:latest ./backend
          docker push cherkaoui97/labmetrixis_fillrouge_backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t cherkaoui97/labmetrixis_fillrouge_frontend:latest ./frontend
          docker push cherkaoui97/labmetrixis_fillrouge_frontend:latest

      # Arrêter les services Docker Compose après les tests
      - name: Stop services
        run: docker-compose down
